NAME = 'Name'
DATE = 'Date'
VALUE = 'Value'
FLEX_VALUE = 'Flex value'
ACCOUNT = 'Account'
CATEGORY = 'Category'
SUBCATEGORY = 'Subcategory'
CURRENCY = 'Currency'
ORIGINAL_CURRENCY = 'Original currency'
POSITION = 'Position'
FLEX_POSITION = 'Flex position'
FLEX_INCOME = 'Flex income'
REMOVE = 'Remove'
APORT = 'Aport'
PRICE = 'Price'
TOTAL = 'Total'

NU = 'Nu'
EASY = 'Easy'
BT = 'BT'
BNB = 'BNB'
BFI = 'BlockFi'
INVESTMENTS = 'Stocks'

FIXED_INCOME = 'Fixed income'
CASH = 'Cash'
REAL_STATE = 'Real state'
CRYPTO = 'Crypto'
STABLECOIN = 'Stablecoin'
US_GROWTH = 'US growth'
US_FINANCES = 'US finances'
US_SUPER_GROWTH = 'US super growth'
BR_GROWTH = 'BR growth'
AXIE = 'Axie'
STAR = 'Star atlas'
THETAN = 'Thetan'
DEFINA = 'Defina'
NFTG = 'NFT games'

INCOME = 'Income'
EXPENSES = 'Expenses'

FROM = 'From'
TO = 'To'

TICKER = 'Ticker'
BUY = 'Buy'
SHARES = 'Shares'
BUY_TAX = 'Buy Tax'
ENTER_DATE = 'Enter date'
TYPE = 'Type'
PURCHASE = 'Purchase'
SALE = 'Sale'
BUY_TAX_CURRENCY = 'Buy Tax Currency'

IN = 'In'
OUT = 'Out'
EXCHANGE = 'Exchange'

DATE_TRESHOLD = 20

COLS = [INCOME, EXPENSES, OUT, IN, EXCHANGE]
